### ISSUE TITLE
Create and Flywheel need updates?

### ISSUE THREAD

**Issue by Mementh** [CuboidDroid/cuboidoutpost-le#1]
**Modpack Version:**
1.0.8

**Describe the bug**
Create is preventing loading of modpack.

**To Reproduce**
download and open

**Expected behavior**
modpack running

**Screenshots**
(https://discord.com/channels/793101707646992404/939097612747943979/939888185561976833)

**Additional context**
updating to most recent versions seems to fix issues

**Comment by CuboidDroid** [comment]
Changed to enhancement as it was only causing a problem due to mementh doing their own upgrades, rather than the pack shipping in a broken state.

Create and Flywheel have, however, been updated to a new version in 1.1.0 which has just been released.
