### ISSUE TITLE
Seed recipe

### ISSUE THREAD

**Issue by Vermula** [CuboidDroid/cuboidoutpost-le#13]
**Modpack Version:**
0.2

**Describe the bug**
Both Agave seed and Coffeebean seed are made with the Quantum Transmutation Chamber, but both are made with the same ingredients, fern and cactus. This makes it automatically produce coffeebean seeds for me.

.

**Comment by MisterWiggly** [comment]
Good catch. I've added a fix for this for the v0.4 update.
