### ISSUE TITLE
Reasonable update requests

### ISSUE THREAD

**Issue by LuciusV** [CuboidDroid/cuboidoutpost-le#2]
I would like to suggest updating some essential mods, and below there are reasons why:

1. **Refined Storage** to 1.9.17  - this version added proper handling of fluids in patterns, and order in which items come to craft became stable. This is essential to some complex automation.
2. **Thermal Expansion** to 1.4 - this adds seal slots to close some of Induction smelter inputs, and automatic processing was a pain to automate without it.
3. Also I strongly suggest to include **Pipez** - especially as you care about modpack performance, **it's not good to force users to use Mekanism pipes as they are becoming extremely laggy very fast in large network.** Please look at mod page performance comparison: https://www.curseforge.com/minecraft/mc-mods/pipez
4. (optional, but will be very handy) **Flux Networks** because no one likes cable mess. OFC with SRG generators it's less problem, but putting individual of these to every machine is not optimum solution, and if there were Flux Networks users can put only that many SRG as they need.

And let me thank you for this awesome modpack, its really fun to play!

**Comment by CuboidDroid** [comment]
1. This will be included in the upcoming 1.1.0 release
2. This will be included in the upcoming 1.1.0 release
3. This will be included in the upcoming 1.1.0 release - gated behind steel so as not to break progression
4. Won't be including this. Powah's Ender Cells, and Ender Gates and Player Transmitters provide comparable wireless power capabilities

**Comment by CuboidDroid** [comment]
Released in v1.1.0
