### ISSUE TITLE
Ex compressum sieves and autosieves are not "waterloggable"

### ISSUE THREAD

**Issue by SiriosDev** [CuboidDroid/cuboidoutpost-le#3]
Version 1.0.10

Ex compressum sieves and autosieves are not "waterloggable"

Contrary to what the jei says, when I right-click with the water bucket nothing happens (torch disaster excluded😅)

**Comment by CuboidDroid** [comment]
I haven't tried on the auto sieve myself, but for heavy sieve I think you can it out into a puddle of water instead

**Comment by SiriosDev** [comment]
Ok actually putting it in an existing water source works, so it doesn't just work using the bucket

**Comment by CuboidDroid** [comment]
I'm going to close this one - I've done a bit of looking on the Ex Compressum issue list and it seems that the "place it into water" mechanic is what's supported, and water logging by right-clicking with a bucket is not supported (and from what I can see, there are no plans for it to be changed)
