### ISSUE TITLE
Creative wireless crafting grid doesn't have recipe

### ISSUE THREAD

**Issue by ariecos** [CuboidDroid/cuboidoutpost-le#5]
**Is your feature request related to a problem? Please describe.**
Creative Wireless Crafting Grid from Refined Storage Addons does not have crafting recipe like other creative grids.

**Describe the solution you'd like**
Attached creative_refined.js file added to the pack

**Describe alternatives you've considered**
N/A
[kubejs.zip](https://github.com/CuboidDroid/cuboidoutpost-le/files/8097559/kubejs.zip)
.

**Comment by CuboidDroid** [comment]
This will be included in the upcoming 1.1.0 release

**Comment by CuboidDroid** [comment]
Released in v.1.1.0
