### ISSUE TITLE
Possible translation

### ISSUE THREAD

**Issue by AndyDL24** [CuboidDroid/cuboidoutpost-le#6]
Hi, I plan to translate the quests of the game in Italian according to you where can I go to see to translate the texts?
Is it possible to do something like this?
Thanks for your time.

**Comment by CuboidDroid** [comment]
Hi. I'm away this weekend so can't check right now exactly where the files are, but I think they are all under config/ftbquests - hopefully it's clear enough which bits need translating. If you make changes you should see them in your game when you run it. I will need to make a few changes to support multilingual properly, but if you get those updated and send them over, I will get it all set up properly. Thanks!

**Comment by AndyDL24** [comment]
Hi, ok I check better where the files are and if I can complete it I send you the files so you can implement them, thanks to you.

**Comment by DelfCo** [comment]
The source files for quest texts are all in the same directory: https://github.com/CuboidDroid/cuboidoutpost-le/tree/main/src/overrides/config/ftbquests/quests/chapters

Sorry, but I don't know how to organize the files for a translated version. We might have to look at some other packs on GitHub that already have translations, and see how it's done.

**Comment by AndyDL24** [comment]
Hi, yes I have seen the files and I am already at a good point.  I'm sorry they don't work directly which is a shame.  However as you told me you can look for other packages to see if it can be done.  thank you very much have a nice day.

**Comment by CuboidDroid** [comment]
Yes, I believe I have a way of doing it, so I'm looking forward to trying it out :-)

**Comment by AndyDL24** [comment]
Hi, as soon as I finish everything I write to you directly here and I create a link where you can download the files.  However, I am also translating the file outside that folder.

**Comment by AndyDL24** [comment]
Hello I finished the translation of the quests, many machineries are in original language, I thought that the game is started in English so only the explanations of the quests I have physically translated. I created a pull request so you can see where I put the files. Thanks

**Comment by CuboidDroid** [comment]
Thank you! I'll work on getting this into the pack as soon as I get a chance. It looks great - thank you so much for going to this effort - I really appreciate it.

**Comment by CuboidDroid** [comment]
Released in 1.1.2. Thanks!
